services:
    postgresql:
        container_name: "postgresql"
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_DB: 'course_rest_api'
            POSTGRES_USER: 'laravel'
            POSTGRES_PASSWORD: 'l4r4v3l4dm1n'
            PGDATA: '/var/lib/postgresql/data/pgdata'
        networks:
            - network_postgresql
        volumes:
            -   'postgresql_volume:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 20s
            retries: 3
networks:
    network_postgresql:
        name: 'network_postgresql'

volumes:
    postgresql_volume:
        name: 'postgresql_volume'
