services:
#    laravel:
#        build:
#            context: .
#            dockerfile: ./Dockerfile
#        container_name: "rest-api-codeinajax"
#        ports:
#            -   "8080:80"
#        networks:
#            - network_laravel
#            - network_postgresql
#        volumes:
#            - '.env:/var/www/html/.env:rw'


    postgresql:
        container_name: "postgresql"
        image: postgres:13-alpine
        restart: always
        env_file:
            -   ./.env.pgsql
        networks:
            - network_postgresql
        volumes:
            -   'postgresql_volume:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 20s
            retries: 3
networks:
    network_postgresql:
        name: 'network_postgresql'
#    network_laravel:
#        name: 'network_laravel'

volumes:
    postgresql_volume:
        name: 'postgresql_volume'
