services:
#    laravel:
#        build:
#            context: .
#            dockerfile: ./Dockerfile
#        container_name: "rest-api-codeinajax"
#        ports:
#            -   "8080:80"
#        networks:
#            - network_laravel
#            - network_postgresql
#        volumes:
#            - '.env:/var/www/html/.env:rw'


    postgresql:
        container_name: "postgresql"
        image: postgres:13-alpine
        restart: unless-stopped
        env_file:
            -   ./.env.pgsql
        networks:
            - network_postgresql
        volumes:
            -   'postgresql_volume:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 20s
            retries: 3

    minio:
        container_name: "minio"
        image: "bitnami/minio:latest"
        restart: unless-stopped
        env_file:
            -   ./.env.minio
        volumes:
            -   'minio_volume:/bitnami/minio/data'
        ports:
            -   '9000:9000'
            -   '9001:9001'
        networks:
            - network_minio

networks:
    network_postgresql:
        name: 'network_postgresql'
    network_minio:
        name: 'network_minio'
#    network_laravel:
#        name: 'network_laravel'

volumes:
    postgresql_volume:
        name: 'postgresql_volume'
    minio_volume:
        name: 'minio_volume'
